feat(get_object): use `MINIO_BUCKET` env-var
deis/slugrunner pull request #66
Opened 2017-08-02 21:56 UTC by drgarcia1986

Use MINIO_BUCKET environment variable to define the bucket name for minio storage type
instead of hardcoded `git`

If there isnt a value on MINIO_BUCKET var, get_object will use `git` by default

2017-08-02 21:56 UTC, deis-admin commented
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

2017-08-03 15:41 UTC, mboersma commented
Jenkins, add to whitelist.

2017-08-03 16:29 UTC, mboersma requested changes

2017-08-03 16:29 UTC, mboersma commented on rootfs/bin/get_object
> +  MINION_BUCKET_NAME=${MINIO_BUCKET:-git}
Could you make this `MINIO_BUCKET_NAME` (not `MINION`)?

Sorry for the CI failures--Jenkins is having a bad day and I'm babysitting him. I think this is actually passing and I'll make sure it goes green.

2017-08-03 16:37 UTC, drgarcia1986 commented on rootfs/bin/get_object
> +  MINION_BUCKET_NAME=${MINIO_BUCKET:-git}
Oh my gosh! I was sleeping when I write this 😂 sorry!
I hope Jenkins get well soon :P

2017-08-03 16:38 UTC, drgarcia1986 commented on rootfs/bin/get_object
> +  MINION_BUCKET_NAME=${MINIO_BUCKET:-git}
Done

2017-08-03 16:43 UTC, drgarcia1986 commented
@mboersma updated! could you check again?

2017-08-03 16:44 UTC, mboersma approved these changes

2017-08-08 16:42 UTC, vdice approved these changes

2017-08-08 16:42 UTC, merged